data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: testaks
---
data:
  host.master: aHprOGY1a0Y4UVhkajFGVk5kMFpPU3kzTElMblJSSjVaMFljTkQ0WXZ6LWtBekZ1a1k1UWNnPT0=
  host.function.default: Qlk5cnlYQ2JEUDVXYkFVUElKMFVHeG9fTXV3UjJnUEVFTkc2Y3U0eWZIVDhBekZ1V1JGSmtBPT0=
  host.systemKey.default: QU52a0VjeEtsVUxMdjB0N2FkcjUyNjNIM2xDM1U1X0lNaUVvbEJOakhnck1BekZ1QVdVcTlBPT0=
  functions.createadvertisement.default: UHNhMy1XaHZzSm5qbXl0bGZoRkVBMElVX0E5ejdjUUFmcTVxZ3I1ckM4TkJBekZ1dG0zNTFRPT0=
  functions.deleteadvertisement.default: YzdaRGNva0c5eGR0STM1ZzkzVS0wNFFuREZKWDk2MHd5WklndkV3TWRCTk1BekZ1UF9UNXRRPT0=
  functions.getadvertisement.default: cDVKdXczRGJHbWN4V1RBeW5tRWI1SkQzMmoyQVBvb1pPZVdhWk93aG5YdUxBekZ1ZDVsLVFBPT0=
  functions.getadvertisements.default: ZC1tUk9kRS16dk5BdWtzWDBKNmhhVUNKWHhqQlZ1X1Q0SDRBUEpsTVl5LXFBekZ1QXQzQnVBPT0=
  functions.getpost.default: dHlLUjRBd1ZRU21uMWF0Ymx6ejVhU2ZrLVpuWjZFNkNTR2tRVGJQQ0pNZThBekZ1NkRRc3JBPT0=
  functions.getposts.default: Mm51dlNCRjNxVExvODk1T29oZF9Jak1UVm40dkxKNHE3blhmRWJ1SXNFTjdBekZ1MGltcTJ3PT0=
  functions.updateadvertisement.default: eWZUeE5MT1hjcWYtaFB4VW9FS2QzTkdlLUFxM3ktVW8tbnRrcjlGZVl0aF9BekZ1ZVIxZWpRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-testaks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testaks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: testaks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testaks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: testaks-http
spec:
  replicas: 0
  selector:
    app: testaks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testaks-http
  labels:
    app: testaks-http
spec:
  replicas: 0
  selector:
    matchLabels:
      app: testaks-http
  template:
    metadata:
      labels:
        app: testaks-http
    spec:
      containers:
      - name: testaks-http
        image: registrykhoalnn.azurecr.io/testaks:v1
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-testaks
        envFrom:
        - secretRef:
            name: testaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: testaks-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testaks
  labels:
    app: testaks
spec:
  replicas: 0
  selector:
    matchLabels:
      app: testaks
  template:
    metadata:
      labels:
        app: testaks
    spec:
      containers:
      - name: testaks
        image: registrykhoalnn.azurecr.io/testaks:v1
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: testaks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: testaks-function-keys-identity-svc-act


